

use master
go
ALTER DATABASE ERP2800PMBK SET SINGLE_USER WITH ROLLBACK IMMEDIATE 
go
ALTER DATABASE ERP2800PMBK COLLATE Latin1_General_100_CI_AS
go
ALTER DATABASE ERP2800PMBK SET MULTI_USER
go