

WITH X as (
SELECT * FROM CO WHERE LEFT(DOCSTMM,3) IN ('DIY','COM')
)
SELECT * FROM X



-- ต้องใช้เป็นแบบนี้ห้ามใช้เป็น AS

WITH X AS (
SELECT DOCSTMM ,QTY = COUNT(PRODUCTID)  FROM ITEMCO WHERE LEFT(DOCSTMM,3) = 'DIY' GROUP BY DOCSTMM
)
SELECT * FROM X